language: node_js
node_js:
   - '12.13.0'
 # Travis-CI Caching
cache:
  directories:
    - node_modules
install:
    - npm install
script:
  - npm run build
after_script:
  - cd ./dist
  - git init
  - git config user.name "duzibo"
  - git config user.email "duzibo@bytedance.com"
  - git add .
  - git commit -m "Update tools"
  - git push --force --quiet "https://${TOKEN}" master:${BRANCH}
# E: Build LifeCycle
branches:
  only: 
    - master

