language: node_js
node_js:
   - '12.13.0'
 # Travis-CI Caching
cache:
  directories:
    - node_modules
install:
    - npm install
script:
  - npm run build
after_script:
  - cd ./dist
  - git init
  - git config user.name "iwantyou"
  - git config user.email "649237053@qq.com"
  - git add .
  - git commit -m "TravisCI"
  # Github Pages
  - git push --force --quiet "https://${TOKEN}@github.com/iwantyou/webpack.git" master:master
# E: Build LifeCycle
branches:
  only: 
    - master

